Update importapis.yaml

diff --git a/.github/workflows/importapis.yaml b/.github/workflows/importapis.yaml
--- a/.github/workflows/importapis.yaml
+++ b/.github/workflows/importapis.yaml
@@ -1,37 +1,29 @@
-name: Validate OpenAPI Definitions
+name: Import APIs to APIM
 
-on: push
+on:
+  push:
+    branches:
+      - main
 
 jobs:
-  validate:
+  swagger-validation:
     runs-on: ubuntu-latest
+    name: Swagger Validation
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
+      - uses: actions/checkout@v2
       - name: Validate OpenAPI definitions
         run: |
-          mkdir invalid-openapi
-          for f in $(find ./apis -type f -name "*.yaml"); do
-            swagger-cli validate $f || echo "$f" >> ./invalid-openapi/Openapi-API-definition-Invalid
+          npm install -g @apidevtools/swagger-cli
+          cd apis
+          invalid_files=""
+          for file in *.yaml; do
+            if ! swagger-cli validate "$file"; then
+              invalid_files+="$file "
+            fi
           done
-
-      - name: Email invalid OpenAPI definitions
-        uses: dawidd6/action-send-mail@v3
-        with:
-          server_address: smtp.office365.com
-          server_port: 587
-          username: ${{ secrets.EMAIL_USERNAME }}
-          password: ${{ secrets.EMAIL_PASSWORD }}
-          from: <sender-email-address>
-          subject: Invalid OpenAPI definitions
-          to: jlaws12@liberty.edu
-          body: |
-            Please find attached the list of invalid OpenAPI definitions.
-          attachments: |
-            ./invalid-openapi/Openapi-API-definition-Invalid
-
+          echo "$invalid_files" > Openapi-API-definition-Invalid
+        working-directory: ${{ github.workspace }}
 
       - name: Login to Azure
         uses: azure/login@v1
